// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_joC_oTOiLyHOo7ID-YO6Fuly04lO7MY',
    appId: '1:708333523189:web:fd49c17a28f70ba0a235bc',
    messagingSenderId: '708333523189',
    projectId: 'nightpoint-cdc0d',
    authDomain: 'nightpoint-cdc0d.firebaseapp.com',
    storageBucket: 'nightpoint-cdc0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--WrT_2WgOZib5n4ZWJW4zQO8HSkQlJA',
    appId: '1:708333523189:android:aa41a52406cc8c38a235bc',
    messagingSenderId: '708333523189',
    projectId: 'nightpoint-cdc0d',
    storageBucket: 'nightpoint-cdc0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKq94BQwQh9W1AiHXcwm2r5uTFJOH5OA',
    appId: '1:708333523189:ios:1cdc684cdf3edb45a235bc',
    messagingSenderId: '708333523189',
    projectId: 'nightpoint-cdc0d',
    storageBucket: 'nightpoint-cdc0d.firebasestorage.app',
    iosBundleId: 'com.example.nightpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKq94BQwQh9W1AiHXcwm2r5uTFJOH5OA',
    appId: '1:708333523189:ios:1cdc684cdf3edb45a235bc',
    messagingSenderId: '708333523189',
    projectId: 'nightpoint-cdc0d',
    storageBucket: 'nightpoint-cdc0d.firebasestorage.app',
    iosBundleId: 'com.example.nightpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_joC_oTOiLyHOo7ID-YO6Fuly04lO7MY',
    appId: '1:708333523189:web:29a0d84a9fb6141ea235bc',
    messagingSenderId: '708333523189',
    projectId: 'nightpoint-cdc0d',
    authDomain: 'nightpoint-cdc0d.firebaseapp.com',
    storageBucket: 'nightpoint-cdc0d.firebasestorage.app',
  );
}
